// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('classe1914.game').factory('MainMenu', [
    '$rootScope', function($rootScope) {
      var MainMenu;
      return new (MainMenu = (function() {
        function MainMenu() {
          this.music;
          this.playButton;
          this.cursors;
          this.spacebar;
          this.b_key;
          this.z_key;
          this.click;
        }

        MainMenu.prototype.create = function() {
          this.physics.startSystem(Phaser.Physics.ARCADE);
          this.cursors = this.input.keyboard.createCursorKeys();
          this.spacebar = this.input.keyboard.addKey(Phaser.Keyboard.SPACEBAR);
          this.b_key = this.input.keyboard.addKey(Phaser.Keyboard.B);
          this.z_key = this.input.keyboard.addKey(Phaser.Keyboard.Z);
          this.f_key = this.input.keyboard.addKey(Phaser.Keyboard.F);
          this.click = this.input.activePointer;
          this.startButton();
          return this.world.setBounds(0, 0, 5000, 1673);
        };

        MainMenu.prototype.startButton = function() {
          this.playButton = this.add.button(this.world.centerX - 96, 300, 'playButton', this.startgame, this, 2, 1, 0);
          return this.playButton.input.useHandCursor = true;
        };

        MainMenu.prototype.update = function() {};

        MainMenu.prototype.startgame = function(pointer) {
          return this.state.start('Game');
        };

        return MainMenu;

      })());
    }
  ]);

}).call(this);

//# sourceMappingURL=MainMenu.js.map
