// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('classe1914.game').factory('MainMenu', [
    '$rootScope', function($rootScope) {
      var MainMenu;
      return new (MainMenu = (function() {
        function MainMenu() {
          this.music;
          this.playButton;
        }

        MainMenu.prototype.create = function() {
          return this.startButton();
        };

        MainMenu.prototype.startButton = function() {
          this.playButton = this.add.button(this.world.centerX - 96, 300, 'playButton', this.startgame, this, 2, 1, 0);
          return this.playButton.input.useHandCursor = true;
        };

        MainMenu.prototype.update = function() {};

        MainMenu.prototype.startgame = function(pointer) {
          return this.state.start('Game');
        };

        return MainMenu;

      })());
    }
  ]);

}).call(this);

//# sourceMappingURL=MainMenu.js.map
