// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('classe1914.constant').constant('constant.games.preload', {
    bar: '/games/common/img/c14g_preloader-bar.png',
    barContainer: '/games/common/img/c14g_preloader-bar-container.png'
  });

}).call(this);

//# sourceMappingURL=preload.js.map
